-- ===========================================================================
-- Seed: migrate the existing static Social Media Creatives into the CMS.
--
-- Generated by scripts/cms-gen-seed-sql.mjs — do not edit by hand.
-- Safe to run more than once: brands that already exist are skipped, so this
-- will never duplicate content or overwrite edits you have made in the CMS.
-- ===========================================================================

do $$
declare
  v_brand_id uuid;
  v_item_id  uuid;
begin

  -- Ignitol — 7 posts, 16 images
  if not exists (select 1 from public.brands where section = 'social' and slug = 'ignitol') then
    insert into public.brands (section, slug, name, industry, blurb, accent, logo_url, bg_url, pinned, position, published)
    values ('social', 'ignitol', 'Ignitol', 'Technology & SaaS', 'Launch campaigns and product creatives that made a young software brand feel established.', '#c2410c', NULL, NULL, false, 0, true)
    returning id into v_brand_id;

    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 0, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/ignitol/poster-01.webp', 1080, 1350, 'Ignitol social media creative №01 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 1, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/ignitol/poster-02.webp', 1080, 1350, 'Ignitol social media creative №02 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/ignitol/poster-03.webp', 1080, 1350, 'Ignitol social media creative №03 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/ignitol/poster-04.webp', 1080, 1350, 'Ignitol social media creative №04 — designed by Muhammad Umaid Sadiq', 2),
      (v_item_id, '/portfolio/social/ignitol/poster-05.webp', 1080, 1350, 'Ignitol social media creative №05 — designed by Muhammad Umaid Sadiq', 3);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 2, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/ignitol/poster-06.webp', 1080, 1350, 'Ignitol social media creative №06 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 3, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/ignitol/poster-07.webp', 1080, 1350, 'Ignitol social media creative №07 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/ignitol/poster-08.webp', 1080, 1350, 'Ignitol social media creative №08 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/ignitol/poster-09.webp', 1080, 1350, 'Ignitol social media creative №09 — designed by Muhammad Umaid Sadiq', 2);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 4, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/ignitol/poster-10.webp', 1080, 1350, 'Ignitol social media creative №10 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 5, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/ignitol/poster-11.webp', 1080, 1350, 'Ignitol social media creative №11 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/ignitol/poster-12.webp', 1080, 1350, 'Ignitol social media creative №12 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/ignitol/poster-13.webp', 1080, 1350, 'Ignitol social media creative №13 — designed by Muhammad Umaid Sadiq', 2),
      (v_item_id, '/portfolio/social/ignitol/poster-14.webp', 1080, 1350, 'Ignitol social media creative №14 — designed by Muhammad Umaid Sadiq', 3),
      (v_item_id, '/portfolio/social/ignitol/poster-15.webp', 1080, 1350, 'Ignitol social media creative №15 — designed by Muhammad Umaid Sadiq', 4);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 6, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/ignitol/poster-16.webp', 1080, 1350, 'Ignitol social media creative №16 — designed by Muhammad Umaid Sadiq', 0);
  end if;

  -- Travmark — 6 posts, 12 images
  if not exists (select 1 from public.brands where section = 'social' and slug = 'travmark') then
    insert into public.brands (section, slug, name, industry, blurb, accent, logo_url, bg_url, pinned, position, published)
    values ('social', 'travmark', 'Travmark', 'Travel & Tourism', 'Destination-led social design that turned wanderlust into a steady stream of enquiries.', '#0e7490', NULL, NULL, false, 1, true)
    returning id into v_brand_id;

    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 0, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/travmark/poster-01.webp', 1080, 1350, 'Travmark social media creative №01 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 1, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/travmark/poster-02.webp', 1080, 1350, 'Travmark social media creative №02 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/travmark/poster-03.webp', 1080, 1350, 'Travmark social media creative №03 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/travmark/poster-04.webp', 1080, 1350, 'Travmark social media creative №04 — designed by Muhammad Umaid Sadiq', 2),
      (v_item_id, '/portfolio/social/travmark/poster-05.webp', 1080, 1350, 'Travmark social media creative №05 — designed by Muhammad Umaid Sadiq', 3);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 2, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/travmark/poster-06.webp', 1080, 1350, 'Travmark social media creative №06 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 3, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/travmark/poster-07.webp', 1080, 1350, 'Travmark social media creative №07 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/travmark/poster-08.webp', 1080, 1350, 'Travmark social media creative №08 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/travmark/poster-09.webp', 1080, 1350, 'Travmark social media creative №09 — designed by Muhammad Umaid Sadiq', 2);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 4, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/travmark/poster-10.webp', 1080, 1350, 'Travmark social media creative №10 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 5, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/travmark/poster-11.webp', 1080, 1350, 'Travmark social media creative №11 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/travmark/poster-12.webp', 1080, 1350, 'Travmark social media creative №12 — designed by Muhammad Umaid Sadiq', 1);
  end if;

  -- KRA Clinic — 6 posts, 14 images
  if not exists (select 1 from public.brands where section = 'social' and slug = 'kra-clinic') then
    insert into public.brands (section, slug, name, industry, blurb, accent, logo_url, bg_url, pinned, position, published)
    values ('social', 'kra-clinic', 'KRA Clinic', 'Healthcare', 'Calm, trustworthy creatives for a clinic — clinical credibility without the cold edge.', '#047857', NULL, NULL, false, 2, true)
    returning id into v_brand_id;

    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 0, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/kra-clinic/poster-01.webp', 1080, 1350, 'KRA Clinic social media creative №01 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 1, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/kra-clinic/poster-02.webp', 1080, 1350, 'KRA Clinic social media creative №02 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/kra-clinic/poster-03.webp', 1080, 1350, 'KRA Clinic social media creative №03 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/kra-clinic/poster-04.webp', 1080, 1350, 'KRA Clinic social media creative №04 — designed by Muhammad Umaid Sadiq', 2),
      (v_item_id, '/portfolio/social/kra-clinic/poster-05.webp', 1080, 1350, 'KRA Clinic social media creative №05 — designed by Muhammad Umaid Sadiq', 3);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 2, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/kra-clinic/poster-06.webp', 1080, 1350, 'KRA Clinic social media creative №06 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 3, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/kra-clinic/poster-07.webp', 1080, 1350, 'KRA Clinic social media creative №07 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/kra-clinic/poster-08.webp', 1080, 1350, 'KRA Clinic social media creative №08 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/kra-clinic/poster-09.webp', 1080, 1350, 'KRA Clinic social media creative №09 — designed by Muhammad Umaid Sadiq', 2);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 4, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/kra-clinic/poster-10.webp', 1080, 1350, 'KRA Clinic social media creative №10 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 5, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/kra-clinic/poster-11.webp', 1080, 1350, 'KRA Clinic social media creative №11 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/kra-clinic/poster-12.webp', 1080, 1350, 'KRA Clinic social media creative №12 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/kra-clinic/poster-13.webp', 1080, 1350, 'KRA Clinic social media creative №13 — designed by Muhammad Umaid Sadiq', 2),
      (v_item_id, '/portfolio/social/kra-clinic/poster-14.webp', 1080, 1350, 'KRA Clinic social media creative №14 — designed by Muhammad Umaid Sadiq', 3);
  end if;

  -- Volt Matrix — 5 posts, 10 images
  if not exists (select 1 from public.brands where section = 'social' and slug = 'volt-matrix') then
    insert into public.brands (section, slug, name, industry, blurb, accent, logo_url, bg_url, pinned, position, published)
    values ('social', 'volt-matrix', 'Volt Matrix', 'Energy & Electronics', 'Bold, high-contrast designs that gave an electronics brand a confident, modern voice.', '#4338ca', NULL, NULL, false, 3, true)
    returning id into v_brand_id;

    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 0, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/volt-matrix/poster-01.webp', 1080, 1350, 'Volt Matrix social media creative №01 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 1, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/volt-matrix/poster-02.webp', 1080, 1350, 'Volt Matrix social media creative №02 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/volt-matrix/poster-03.webp', 1080, 1350, 'Volt Matrix social media creative №03 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/volt-matrix/poster-04.webp', 1080, 1350, 'Volt Matrix social media creative №04 — designed by Muhammad Umaid Sadiq', 2),
      (v_item_id, '/portfolio/social/volt-matrix/poster-05.webp', 1080, 1350, 'Volt Matrix social media creative №05 — designed by Muhammad Umaid Sadiq', 3);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 2, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/volt-matrix/poster-06.webp', 1080, 1350, 'Volt Matrix social media creative №06 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 3, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/volt-matrix/poster-07.webp', 1080, 1350, 'Volt Matrix social media creative №07 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/volt-matrix/poster-08.webp', 1080, 1350, 'Volt Matrix social media creative №08 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/volt-matrix/poster-09.webp', 1080, 1350, 'Volt Matrix social media creative №09 — designed by Muhammad Umaid Sadiq', 2);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 4, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/volt-matrix/poster-10.webp', 1080, 1350, 'Volt Matrix social media creative №10 — designed by Muhammad Umaid Sadiq', 0);
  end if;

  -- FM Foods — 6 posts, 15 images
  if not exists (select 1 from public.brands where section = 'social' and slug = 'fm-foods') then
    insert into public.brands (section, slug, name, industry, blurb, accent, logo_url, bg_url, pinned, position, published)
    values ('social', 'fm-foods', 'FM Foods', 'Food & Beverage', 'Appetite-first social creatives — warm, vivid, and built to stop the scroll.', '#b45309', NULL, NULL, false, 4, true)
    returning id into v_brand_id;

    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 0, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/fm-foods/poster-01.webp', 1080, 1350, 'FM Foods social media creative №01 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 1, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/fm-foods/poster-02.webp', 1080, 1350, 'FM Foods social media creative №02 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/fm-foods/poster-03.webp', 1080, 1350, 'FM Foods social media creative №03 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/fm-foods/poster-04.webp', 1080, 1350, 'FM Foods social media creative №04 — designed by Muhammad Umaid Sadiq', 2),
      (v_item_id, '/portfolio/social/fm-foods/poster-05.webp', 1080, 1350, 'FM Foods social media creative №05 — designed by Muhammad Umaid Sadiq', 3);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 2, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/fm-foods/poster-06.webp', 1080, 1350, 'FM Foods social media creative №06 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 3, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/fm-foods/poster-07.webp', 1080, 1350, 'FM Foods social media creative №07 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/fm-foods/poster-08.webp', 1080, 1350, 'FM Foods social media creative №08 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/fm-foods/poster-09.webp', 1080, 1350, 'FM Foods social media creative №09 — designed by Muhammad Umaid Sadiq', 2);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 4, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/fm-foods/poster-10.webp', 1080, 1350, 'FM Foods social media creative №10 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 5, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/fm-foods/poster-11.webp', 1080, 1350, 'FM Foods social media creative №11 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/fm-foods/poster-12.webp', 1080, 1350, 'FM Foods social media creative №12 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/fm-foods/poster-13.webp', 1080, 1350, 'FM Foods social media creative №13 — designed by Muhammad Umaid Sadiq', 2),
      (v_item_id, '/portfolio/social/fm-foods/poster-14.webp', 1080, 1350, 'FM Foods social media creative №14 — designed by Muhammad Umaid Sadiq', 3),
      (v_item_id, '/portfolio/social/fm-foods/poster-15.webp', 1080, 1350, 'FM Foods social media creative №15 — designed by Muhammad Umaid Sadiq', 4);
  end if;

  -- AIR Automotive — 6 posts, 11 images
  if not exists (select 1 from public.brands where section = 'social' and slug = 'air-automotive') then
    insert into public.brands (section, slug, name, industry, blurb, accent, logo_url, bg_url, pinned, position, published)
    values ('social', 'air-automotive', 'AIR Automotive', 'Automotive', 'Sleek, premium automotive design that matched the engineering it was selling.', '#1f2937', NULL, NULL, false, 5, true)
    returning id into v_brand_id;

    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 0, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/air-automotive/poster-01.webp', 1080, 1350, 'AIR Automotive social media creative №01 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 1, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/air-automotive/poster-02.webp', 1080, 1350, 'AIR Automotive social media creative №02 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/air-automotive/poster-03.webp', 1080, 1350, 'AIR Automotive social media creative №03 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/air-automotive/poster-04.webp', 1080, 1350, 'AIR Automotive social media creative №04 — designed by Muhammad Umaid Sadiq', 2),
      (v_item_id, '/portfolio/social/air-automotive/poster-05.webp', 1080, 1350, 'AIR Automotive social media creative №05 — designed by Muhammad Umaid Sadiq', 3);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 2, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/air-automotive/poster-06.webp', 1080, 1350, 'AIR Automotive social media creative №06 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 3, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/air-automotive/poster-07.webp', 1080, 1350, 'AIR Automotive social media creative №07 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/air-automotive/poster-08.webp', 1080, 1350, 'AIR Automotive social media creative №08 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/air-automotive/poster-09.webp', 1080, 1350, 'AIR Automotive social media creative №09 — designed by Muhammad Umaid Sadiq', 2);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 4, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/air-automotive/poster-10.webp', 1080, 1350, 'AIR Automotive social media creative №10 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 5, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/air-automotive/poster-11.webp', 1080, 1350, 'AIR Automotive social media creative №11 — designed by Muhammad Umaid Sadiq', 0);
  end if;

  -- Noor Accounting — 4 posts, 9 images
  if not exists (select 1 from public.brands where section = 'social' and slug = 'noor-accounting') then
    insert into public.brands (section, slug, name, industry, blurb, accent, logo_url, bg_url, pinned, position, published)
    values ('social', 'noor-accounting', 'Noor Accounting', 'Finance & Accounting', 'Clean, reassuring financial creatives that made a numbers business feel human.', '#065f46', NULL, NULL, false, 6, true)
    returning id into v_brand_id;

    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 0, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/noor-accounting/poster-01.webp', 1080, 1350, 'Noor Accounting social media creative №01 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 1, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/noor-accounting/poster-02.webp', 1080, 1350, 'Noor Accounting social media creative №02 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/noor-accounting/poster-03.webp', 1080, 1350, 'Noor Accounting social media creative №03 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/noor-accounting/poster-04.webp', 1080, 1350, 'Noor Accounting social media creative №04 — designed by Muhammad Umaid Sadiq', 2),
      (v_item_id, '/portfolio/social/noor-accounting/poster-05.webp', 1080, 1350, 'Noor Accounting social media creative №05 — designed by Muhammad Umaid Sadiq', 3);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 2, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/noor-accounting/poster-06.webp', 1080, 1350, 'Noor Accounting social media creative №06 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 3, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/noor-accounting/poster-07.webp', 1080, 1350, 'Noor Accounting social media creative №07 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/noor-accounting/poster-08.webp', 1080, 1350, 'Noor Accounting social media creative №08 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/noor-accounting/poster-09.webp', 1080, 1350, 'Noor Accounting social media creative №09 — designed by Muhammad Umaid Sadiq', 2);
  end if;

  -- OptiLuxe — 6 posts, 13 images
  if not exists (select 1 from public.brands where section = 'social' and slug = 'optiluxe') then
    insert into public.brands (section, slug, name, industry, blurb, accent, logo_url, bg_url, pinned, position, published)
    values ('social', 'optiluxe', 'OptiLuxe', 'Eyewear & Retail', 'Editorial eyewear campaigns with a luxe, fashion-forward finish.', '#6d28d9', NULL, NULL, false, 7, true)
    returning id into v_brand_id;

    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 0, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/optiluxe/poster-01.webp', 1080, 1350, 'OptiLuxe social media creative №01 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 1, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/optiluxe/poster-02.webp', 1080, 1350, 'OptiLuxe social media creative №02 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/optiluxe/poster-03.webp', 1080, 1350, 'OptiLuxe social media creative №03 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/optiluxe/poster-04.webp', 1080, 1350, 'OptiLuxe social media creative №04 — designed by Muhammad Umaid Sadiq', 2),
      (v_item_id, '/portfolio/social/optiluxe/poster-05.webp', 1080, 1350, 'OptiLuxe social media creative №05 — designed by Muhammad Umaid Sadiq', 3);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 2, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/optiluxe/poster-06.webp', 1080, 1350, 'OptiLuxe social media creative №06 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 3, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/optiluxe/poster-07.webp', 1080, 1350, 'OptiLuxe social media creative №07 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/optiluxe/poster-08.webp', 1080, 1350, 'OptiLuxe social media creative №08 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/optiluxe/poster-09.webp', 1080, 1350, 'OptiLuxe social media creative №09 — designed by Muhammad Umaid Sadiq', 2);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 4, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/optiluxe/poster-10.webp', 1080, 1350, 'OptiLuxe social media creative №10 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 5, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/optiluxe/poster-11.webp', 1080, 1350, 'OptiLuxe social media creative №11 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/optiluxe/poster-12.webp', 1080, 1350, 'OptiLuxe social media creative №12 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/optiluxe/poster-13.webp', 1080, 1350, 'OptiLuxe social media creative №13 — designed by Muhammad Umaid Sadiq', 2);
  end if;

  -- Paul Brooks — 5 posts, 10 images
  if not exists (select 1 from public.brands where section = 'social' and slug = 'paul-brooks') then
    insert into public.brands (section, slug, name, industry, blurb, accent, logo_url, bg_url, pinned, position, published)
    values ('social', 'paul-brooks', 'Paul Brooks', 'Fashion & Personal Brand', 'A cohesive personal-brand identity translated into a scroll-stopping social presence.', '#9f1239', NULL, NULL, false, 8, true)
    returning id into v_brand_id;

    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 0, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/paul-brooks/poster-01.webp', 1080, 1350, 'Paul Brooks social media creative №01 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 1, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/paul-brooks/poster-02.webp', 1080, 1350, 'Paul Brooks social media creative №02 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/paul-brooks/poster-03.webp', 1080, 1350, 'Paul Brooks social media creative №03 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/paul-brooks/poster-04.webp', 1080, 1350, 'Paul Brooks social media creative №04 — designed by Muhammad Umaid Sadiq', 2),
      (v_item_id, '/portfolio/social/paul-brooks/poster-05.webp', 1080, 1350, 'Paul Brooks social media creative №05 — designed by Muhammad Umaid Sadiq', 3);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 2, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/paul-brooks/poster-06.webp', 1080, 1350, 'Paul Brooks social media creative №06 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 3, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/paul-brooks/poster-07.webp', 1080, 1350, 'Paul Brooks social media creative №07 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/paul-brooks/poster-08.webp', 1080, 1350, 'Paul Brooks social media creative №08 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/paul-brooks/poster-09.webp', 1080, 1350, 'Paul Brooks social media creative №09 — designed by Muhammad Umaid Sadiq', 2);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 4, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/paul-brooks/poster-10.webp', 1080, 1350, 'Paul Brooks social media creative №10 — designed by Muhammad Umaid Sadiq', 0);
  end if;

  -- Fluid Technology International — 6 posts, 12 images
  if not exists (select 1 from public.brands where section = 'social' and slug = 'fluid-technology-international') then
    insert into public.brands (section, slug, name, industry, blurb, accent, logo_url, bg_url, pinned, position, published)
    values ('social', 'fluid-technology-international', 'Fluid Technology International', 'Industrial & Engineering', 'Precise, technical creatives that made complex engineering feel clear and credible.', '#0369a1', NULL, NULL, false, 9, true)
    returning id into v_brand_id;

    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 0, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/fluid-technology-international/poster-01.webp', 1080, 1350, 'Fluid Technology International social media creative №01 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 1, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/fluid-technology-international/poster-02.webp', 1080, 1350, 'Fluid Technology International social media creative №02 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/fluid-technology-international/poster-03.webp', 1080, 1350, 'Fluid Technology International social media creative №03 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/fluid-technology-international/poster-04.webp', 1080, 1350, 'Fluid Technology International social media creative №04 — designed by Muhammad Umaid Sadiq', 2),
      (v_item_id, '/portfolio/social/fluid-technology-international/poster-05.webp', 1080, 1350, 'Fluid Technology International social media creative №05 — designed by Muhammad Umaid Sadiq', 3);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 2, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/fluid-technology-international/poster-06.webp', 1080, 1350, 'Fluid Technology International social media creative №06 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 3, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/fluid-technology-international/poster-07.webp', 1080, 1350, 'Fluid Technology International social media creative №07 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/fluid-technology-international/poster-08.webp', 1080, 1350, 'Fluid Technology International social media creative №08 — designed by Muhammad Umaid Sadiq', 1),
      (v_item_id, '/portfolio/social/fluid-technology-international/poster-09.webp', 1080, 1350, 'Fluid Technology International social media creative №09 — designed by Muhammad Umaid Sadiq', 2);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'image_post', false, 4, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/fluid-technology-international/poster-10.webp', 1080, 1350, 'Fluid Technology International social media creative №10 — designed by Muhammad Umaid Sadiq', 0);
    insert into public.items (brand_id, kind, pinned, position, published)
    values (v_brand_id, 'carousel', false, 5, true) returning id into v_item_id;
    insert into public.item_slides (item_id, image_url, width, height, alt, position) values
      (v_item_id, '/portfolio/social/fluid-technology-international/poster-11.webp', 1080, 1350, 'Fluid Technology International social media creative №11 — designed by Muhammad Umaid Sadiq', 0),
      (v_item_id, '/portfolio/social/fluid-technology-international/poster-12.webp', 1080, 1350, 'Fluid Technology International social media creative №12 — designed by Muhammad Umaid Sadiq', 1);
  end if;

end $$;

-- Verify:
--   select b.name, count(distinct i.id) as posts, count(s.id) as images
--     from public.brands b
--     left join public.items i on i.brand_id = b.id
--     left join public.item_slides s on s.item_id = i.id
--    where b.section = 'social' group by b.name order by b.name;
